include:
  template: Dependency-Scanning.gitlab-ci.yml

image: python:alpine

before_script:
  - pip install -r requirements.txt

pages:
  script:
    - python setup.py install
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - master
